[package]
name = "connect-four-ai-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
connect-four-ai = { path = "../core", version = "0.1.0" }
indicatif = "0.18.0"
clap = { version = "4.5", features = ["derive"] }
