[package]
name = "connect-four-ai"
version = "0.1.0"
edition = "2021"
description = "A high-performance Rust library for a perfect Connect Four AI solver."

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
bincode = "1.3.3"
rayon = "1.10.0"